modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="https://github.com/ErrorCraftLP/Crying-Obsidian/issues"

[[mods]]
modId="cryingobsidian"
version="1.2.1"
displayName="Crying Obsidian"
updateJSONURL="https://raw.githubusercontent.com/ErrorCraftLP/Crying-Obsidian/master/version.json"
displayURL="https://minecraft.curseforge.com/projects/crying-obsidian"
credits="ErrorCraftLP, Mojang (Default Crying Obsidian Texture), carlosyoloful (BDcraft Crying Obsidian Texture)"
authors="ErrorCraftLP"
description='''
Crying Obsidian was intended to be a block that can change your spawn point, but it was never added to the game.
This mod implements this block and adds an item version of it.
'''

[[dependencies.cryingobsidian]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"
    
[[dependencies.cryingobsidian]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
